from enum import Enum


class DbDataTypes(Enum):
    VARCHAR = 'VARCHAR(128)'
    INT = 'INT'
    DOUBLE = 'DECIMAL(5,2)'
    DATETIME = 'DATETIME'


class RandomDataTypes(Enum):
    FEMALEFIRSTNAME = 1
    FEMALELASTNAME = 2
    MALEFIRSTNAME = 3
    MALELASTNAME = 4
    GERMANSTATE = 5
    SPORTSTEAM = 6
    BOATNAME = 7
    BIRTHDATE = 100
    EVENTSTARTTIME = 101
    DISTANCEINMETERS = 200
    RUNINSECONDS = 201
    ID = 300
    MEMBERCOUNT = 301
    SEATS = 302



